### ISSUE TITLE
Add ability for results to be output as JSON

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/metadata-check#12]
Requires:
- [x] Ability to convert `CheckResult` to JSON. Probably also useful if a decoder is also provided.
- [ ] Flags to allow the functionality to be used.

**Comment by colin-nolan** [comment]
JSON encoder/decoder and tests for `CheckResult` completed in https://github.com/wtsi-hgi/metadata-check/blob/e53cce30f048bddda25e0893afab9a00c086a234/mcheck/results/checks_results.py#L80-L81.

**Comment by irinaColgiu** [comment]
Solved  7dd0184d776908497c74c20f3c1c8a0e02534b47
